apiVersion: v1
kind: Secret
metadata:
  name: meet-server-secrets
  namespace: meet
type: Opaque
stringData:
  JWT_SECRET: "enterprise-super-secure-jwt-secret-key-replace-in-prod"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "miniopassword"
  TURN_USERNAME: "meetuser"
  TURN_PASSWORD: "meetsecretpass"
